#!/usr/local/bin/node
const fero = require('fero')

async function main() {
    const chat = await fero('chat', {
        client: true
    })
    await chat.on('connected')
    chat.add({
        type:'createMessage',
        value: {
            from:'9aa6debe-4c80-47d9-b3c4-f962239ec1d4',
            to:'6b84d2db-dd4b-4617-b305-fcac042ff1b5',
            message:'The new tool album is great.'
        }
    })
}

main()
